### ISSUE TITLE
Can't set call list statuses during import

### ISSUE THREAD

**Issue by ThinkFlipp** [Lundalogik/go_import#27]
Just as you can add deal statuses and custom fields during an import, it would be nice to set call list statuses

**Comment by palsson** [comment]
Detta passar inte i go_import eftersom det är mer av typen "konfigurera applikation" än "importera data". 
Anledningen till att det går att skapa custom fields och statusar för affärer är att dom behövs för att importera data på vettigt sätt. 
När/om vi lägger till stöd för import av ringlistor behöver vi också stöd för att skapa statusar för dom. Men inte innan.
