### ISSUE TITLE
Incorrect encoding for source 'csv'

### ISSUE THREAD

**Issue by palsson** [Lundalogik/go_import#35]
Runner.rb and converter.rb should be encoded using UTF-8.

While fixing this, please have a look at the other sources as well. The Excel source is encoded using UTF-8.

**Comment by petterl** [comment]
While reading csv files, it is always assumed that it is an latin1 file:

    data = File.open(file_name, 'r').read.encode('UTF-8',"ISO-8859-1")
    
Maybe a hook in converter for encoding?
